# Generated by Django 4.1.13 on 2024-06-24 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompaniesDividend",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ticker", models.CharField(max_length=255)),
                ("date_of_dividend", models.DateField()),
                ("ex_dividend_date", models.DateField()),
                (
                    "value_of_dividend",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("price_of_dividend", models.BigIntegerField()),
            ],
            options={"db_table": "companies_dividend",},
        ),
        migrations.CreateModel(
            name="CompaniesName",
            fields=[
                (
                    "ticker",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={"db_table": "companies_name",},
        ),
        migrations.CreateModel(
            name="CompaniesPrice",
            fields=[
                (
                    "ticker",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("price", models.CharField(max_length=255)),
            ],
            options={"db_table": "companies_price",},
        ),
        migrations.CreateModel(
            name="UserPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "average_purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dywidendy_GPW.companiesname",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "ticker")},},
        ),
    ]
