# Generated by Django 4.2.13 on 2024-06-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompaniesDividend",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ticker", models.CharField(max_length=255)),
                ("date_of_dividend", models.DateField()),
                (
                    "value_of_dividend",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("multiplier", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={"db_table": "companies_dividend",},
        ),
        migrations.CreateModel(
            name="CompaniesName",
            fields=[
                (
                    "ticker",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={"db_table": "companies_name",},
        ),
        migrations.CreateModel(
            name="CompaniesPrice",
            fields=[
                (
                    "ticker",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("price", models.CharField(max_length=255)),
            ],
            options={"db_table": "companies_price",},
        ),
    ]
