# Generated by Django 4.1.13 on 2024-08-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dywidendy_GPW", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="companiesprice",
            name="dividend_consecutive_years",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="companiesprice",
            name="dividend_growing_consecutive_years",
            field=models.IntegerField(default=0),
        ),
    ]
