# Generated by Django 4.1.13 on 2024-08-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dywidendy_GPW", "0003_companiesprice_dividend_consecutive_years_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companiesprice",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
